pipeline {
    agent any
    parameters {
        
        string(name: 'NODE_IP', defaultValue: '127.0.0.1', description: 'Node IP where this job will be deplyoing app to')
        
        
    }
    tools {
        maven "maven"
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh ${params.NODE_IP}'
            }
        }
    }
}
